#!/bin/sh
#looks up a word in the dictionary
STRING=`awk -v "word=$1" 'BEGIN{print "bzcat 3613404452.dict.bz2 | grep \"^"word"\t\";" }' | sh`
if test "$STRING"
then echo "$STRING" | head -1
exit 1
else
exit 0
fi

